// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_Tdut1sNqxmbQRKVsLT6DAp4br7CN3s',
    appId: '1:556241478728:web:a0695c17987f90d5f9e47d',
    messagingSenderId: '556241478728',
    projectId: 'courseapp-e0f42',
    authDomain: 'courseapp-e0f42.firebaseapp.com',
    storageBucket: 'courseapp-e0f42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBasiXOCzBUIn0HqIv4CwFyIsnyNpLkX7s',
    appId: '1:556241478728:android:cc97d55a9738fbc5f9e47d',
    messagingSenderId: '556241478728',
    projectId: 'courseapp-e0f42',
    storageBucket: 'courseapp-e0f42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOArZjj32Aeih3IqQM_2jsOm8qJtQMCJE',
    appId: '1:556241478728:ios:7cb5f845d1203eb7f9e47d',
    messagingSenderId: '556241478728',
    projectId: 'courseapp-e0f42',
    storageBucket: 'courseapp-e0f42.appspot.com',
    iosClientId: '556241478728-t0kr800eiefsf1o0ga5il3ekd92jj193.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOArZjj32Aeih3IqQM_2jsOm8qJtQMCJE',
    appId: '1:556241478728:ios:82f2dbd2681bc747f9e47d',
    messagingSenderId: '556241478728',
    projectId: 'courseapp-e0f42',
    storageBucket: 'courseapp-e0f42.appspot.com',
    iosClientId: '556241478728-mg3ons2aapkbu570er27flqdf7t21di8.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseProject.RunnerTests',
  );
}
